AWSTemplateFormatVersion: 2010-09-09

Description: >
  Creates an OIDC provider and role for use with GitHub Actions with a built-in permission boundary.

Parameters:
  GithubActionsThumbprint:
    Type: CommaDelimitedList
    Default: D89E3BD43D5D909B47A18977AA9D5CE36CEE184C
    Description: >
      Comma seperated list of thumbprints for GitHub Actions tokens.
  AudienceList:
    Type: CommaDelimitedList
    Default: sts.amazonaws.com
    Description: >
      Comma seperated list of allowed audience for the tokens.
  SubjectClaimFilters:
    Type: CommaDelimitedList
    Default: "repo:gamunu/*"
    Description: >
      Subject claim filter for valid tokens.
  ManagedPolicyARNs:
    Type: CommaDelimitedList
    Default: ""
    Description: Optional comma separated list for arns for managed policies to attach to the role

Resources:
  GitHubActionsPermissionBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GithubActionsPermissionBoundary
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyAllExceptSelectedRegion
            Effect: Deny
            Action: "*"
            Resource: "*"
            Condition:
              StringNotEquals:
                aws:RequestedRegion: "ap-southeast-1"
          - Sid: AllowAssumeRole
            Effect: Allow
            Action:
              - "sts:AssumeRole"
              - "sts:TagSession"
            Resource: "arn:aws:iam::*:role/github/*"

  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: !Ref GithubActionsThumbprint
      ClientIdList: !Ref AudienceList

  GitHubActionsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RoleForGitHubActions
            Effect: Allow
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": !Ref AudienceList
              StringLike:
                "token.actions.githubusercontent.com:sub": !Ref SubjectClaimFilters
      Description: Service Role for use in GitHub Actions
      Path: /github/
      PermissionsBoundary: !Ref GitHubActionsPermissionBoundary
      ManagedPolicyArns: !If 
        - HasManagedPolicies
        - !Ref ManagedPolicyARNs
        - !Ref AWS::NoValue

Conditions:
  HasManagedPolicies: !Not [!Equals [!Join [",", !Ref ManagedPolicyARNs], ""]]

Outputs:
  ServiceRoleARN:
    Description: ARN of service role for use in GitHub actions
    Value: !GetAtt GitHubActionsServiceRole.Arn
  PermissionBoundaryARN:
    Description: ARN of the permission boundary policy
    Value: !Ref GitHubActionsPermissionBoundary